[package]
disabled = true

[golang]
symbol = "G:"

[java]
symbol = "J:"

[nodejs]
symbol = "N:"

[python]
symbol = "P:"

[ruby]
symbol = "R:"

[rust]
symbol = "RS:"

[cmd_duration]
disabled = true

[git_branch]
style = "bold cyan"
